
import os

POLYGON_API_KEY = os.getenv('POLYGON_API_KEY')
MY_S3_BUCKET = os.getenv('PERSONAL_S3_BUCKET_NAME')

PERSONAL_AWS_KEY = os.getenv('PERSONAL_AWS_ACCESS_KEY_ID')
PERSONAL_AWS_SECRET_KEY = os.getenv('PERSONAL_AWS_SECRET_ACCESS_KEY_ID')

FMP_API_KEY = os.getenv('FMP_API_KEY')

# os.getenv('GOOGLE_APP_PASSWORD')

# os.getenv('GMAIL_SENDER_EMAIL')
# os.getenv('GMAIL_RECIEVER_EMAIL')