[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "datafin-dagster"
version = "0.1.0"
dependencies = [
    "dagster",
    "dagster-webserver",
]

[tool.dagster]
module_name = "datafin_dagster"